In [1]:
import numpy as np

In [5]:
a1 = np.array([1,2,3])
print(a1.ndim)
a2 = np.array([[1,2,3],[4,5,6]])
print(a2.ndim)
a3 = np.array([
    [
        [1,2,3],
        [4,5,6]
    ],
    [
        [7,8,9],
        [10,11,12]
    ]
])
print(a3.ndim)

1
2
3


In [8]:
print(a1.shape)
print(a2.shape)
print(a3.shape)

(3,)
(2, 3)
(2, 2, 3)


In [9]:
a4 = a3.reshape((2,6))
print(a4)
print(a4.shape)

[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]
(2, 6)


In [13]:
#a5 = a3.reshape((1,12))
# a5 = a3.reshape((12,))
a5 = a3.flatten()
print(a5)
print(a5.ndim)

[ 1  2  3  4  5  6  7  8  9 10 11 12]
1


In [14]:
count = a3.size
print(count)

12


In [17]:
itemsize = a3.itemsize
print(itemsize)
print(a3.dtype)
print(itemsize*a3.size)

4
int32
48


# 总结
1.数组一般达到三维就已经很复杂了，不太方便计算了，所以我们一般都会把三维以上的数组转换为2维数组来计算。  
2.通过ndarray.ndim可以看到数组的维度   
3.通过ndarray.shape可以看到数组的形状（几行几列），shape时一个元组，里面有几个元素代表是几维数组。   
4.通过ndarray.reshape可以修改数组的形状。条件只有一个，就是修改后的形状的元素个数必须和原来的个数一致。比如原来是(2,6),那么修改完成后可以变成(3,4),但是不能变为(1,4)。reshape不会修改原来数组的形状，它只会将修改后的结果返回。   
5.通过ndarray.size可以看到数组总共有多少个元素   
6.通过ndarray.itemsize可以看到数组中每个元素所占内存的大小，单位是字节  