In [1]:
import numpy as np

In [2]:
# 1.一维数组的索引和切片
a1 = np.arange(10)
# 1.1进行索引操作
print(a1[4])
# 1.2进行切片操作
print(a1[4:6])
# 1.3使用步长
print(a1[::2])
# 1.4使用负数作为索引
print(a1[-1])

4
[4 5]
[0 2 4 6 8]
9


In [3]:
# 2.多维数组
# 也是通过中括号来索引和切片，在中括号中，使用逗号进行分割，逗号前面的是行，逗号后面的是列
# 如果多维数组中只有一个值，那么这个值就是行
a2 = np.random.randint(0,10,size=(4,6))
print(a2)

[[2 8 1 2 2 7]
 [7 3 3 6 7 7]
 [9 6 3 3 0 8]
 [2 1 8 2 5 1]]


In [4]:
# a2[0]
# a2[1:3]
# a2[[0,2,3]]

In [5]:
# a2[2,1]
# print(a2[[1,2],[4,5]])
# print(a2[1:3,4:6])
a2[:,[1,3]]

array([[8, 2],
       [3, 6],
       [6, 3],
       [1, 2]])

# 索引和切片总结
1.如果数组是一维的，那么索引和切片就是和python里的列表是一样的
2.如果数组是多维的（这里以二维为例），那么在中括号中，给两个值，两个值是通过逗号隔开的，逗号前面的是行，逗号后面的是列。如果中括号中只有一个值，那么就是代表行。
3.如果是多维数组（这里以二维为例），那么行的部分和列的部分，都是遵循一维数组的方式，可以使用整形，切片，还可以使用中括号的形式来代表不连续的。比如a[[1,2],[3,4]],那么返回的就是(1,3),(2,4)的两个值。

In [6]:
a1 = np.arange(0,24).reshape((4,6))
print(a1)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]


In [8]:
print(a1<10)
# 会返回一个新的数组，这个数组中的值全部都是bool类型

[[ True  True  True  True  True  True]
 [ True  True  True  True False False]
 [False False False False False False]
 [False False False False False False]]


In [10]:
a1[a1 < 10]

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
a1[(a1 < 5)|(a1 > 10)]

array([ 0,  1,  2,  3,  4, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22,
       23])

# 布尔索引
布尔索引是通过相同数组上的True还是False来进行提取的。提取的条件有多个，那么如果有多个，可以使用&来代表且，用|来代表或，如果有多个条件，那么每个条件都要使用圆括号括起来。

# 值的替换

利用索引做一些值的替换

In [13]:
a3 = np.random.randint(0,10,size=(3,5))
a3

array([[6, 0, 9, 3, 0],
       [3, 8, 7, 2, 7],
       [0, 3, 2, 1, 5]])

In [15]:
a3[1] = np.array([1,2,3,4,5])
a3

array([[6, 0, 9, 3, 0],
       [1, 2, 3, 4, 5],
       [0, 3, 2, 1, 5]])

也可以利用条件索引来实现

In [17]:
a3[a3 < 3] = 1
a3

array([[6, 1, 9, 3, 1],
       [1, 1, 3, 4, 5],
       [1, 3, 1, 1, 5]])

还可以使用where函数来实现

In [18]:
result = np.where(a3<5,0,1)
result

array([[1, 0, 1, 0, 0],
       [0, 0, 0, 0, 1],
       [0, 0, 0, 0, 1]])

# 值的替换总结
1.可以使用索引或者切片来替换
2.使用条件索引来替换
3.使用where函数来实现