In [1]:
import numpy as np

#### 1. 第一题：将np.arange(10)数组中的奇数全部都替换成-1

In [3]:
a1 = np.arange(10)
a1[a1%2!=0] = -1
a1

array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

#### 2. 第二题：有一个4行4列的数组（比如：np.random.randint(0,10,size=(4,4))），请将其中对角线的数取出来形成一个一维数组。提示（使用np.eye）。

In [9]:
a2 = np.random.randint(0,10,size=(4,4))
print(a2)
# np.eye(4)
eye = np.eye(4,dtype=bool)
print(a2[eye])

[[0 8 8 8]
 [6 3 5 1]
 [0 9 0 2]
 [0 3 0 3]]
[0 3 0 3]


#### 3. 有一个4行4列的数组，请取出其中(0,0),(1,2),(3,2)的点。

In [12]:
a3 = np.random.randint(0,10,size=(4,4))
print(a3)
a3[[0,1,3],[0,2,2]]

[[1 4 8 9]
 [5 4 4 2]
 [6 8 5 9]
 [5 1 7 1]]


array([1, 4, 7])

#### 4.有一个4行4列的数组，请取出其中2-3行（包括第3行）的所有数据。

In [14]:
a4 = np.random.randint(0,10,size=(4,4))
print(a4)
a4[2:4]

[[5 9 8 4]
 [0 0 0 0]
 [3 8 8 7]
 [9 9 5 7]]


array([[3, 8, 8, 7],
       [9, 9, 5, 7]])

##### 5. 有一个8行9列的数组，请将其中1-5行（包含第5行）的第8列大于3的数全部都取出来。

In [18]:
a5 = np.random.randint(0,10,size=(8,9))
print(a5)
a5_son = a5[1:6,8]
print(a5_son)
a5_son[a5_son>3]

[[0 7 8 3 8 4 4 8 7]
 [6 1 2 5 4 6 8 6 3]
 [5 4 5 7 2 4 8 2 1]
 [6 9 9 3 7 9 6 9 2]
 [5 6 2 7 5 2 0 1 3]
 [5 3 7 3 6 7 4 5 9]
 [0 3 4 1 0 1 6 6 5]
 [9 5 8 0 2 3 7 7 9]]
[3 1 2 3 9]


array([9])