## 数组与数的计算
在python列表中，想要对列表中所有的元素都加一个数，要么采用map函数，要么循环整个列表进行操作。但是Numpy中的数组可以直接在数组上进行操作

In [1]:
import numpy as np

In [2]:
a1 = np.random.randint(0,10,size=(3,5))
a1

array([[1, 4, 1, 0, 2],
       [2, 9, 8, 4, 3],
       [4, 7, 9, 3, 5]])

In [3]:
print(a1*2)

[[ 2  8  2  0  4]
 [ 4 18 16  8  6]
 [ 8 14 18  6 10]]


相加、相减、相除等也都是类似的

## 数组与数组的计算

In [4]:
# 1.结构相同的数组之间的运算
a1 = np.arange(0,24).reshape((3,8))
a2 = np.random.randint(0,10,size=(3,8))
a3 = a1 + a2
print(a1)
print(a2)
print(a3)

[[ 0  1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14 15]
 [16 17 18 19 20 21 22 23]]
[[9 4 4 0 3 1 5 3]
 [5 5 2 5 7 2 9 9]
 [4 1 1 2 2 6 7 4]]
[[ 9  5  6  3  7  6 11 10]
 [13 14 12 16 19 15 23 24]
 [20 18 19 21 22 27 29 27]]


In [5]:
# 2.与行数相同并且只有一列的数组之间的运算
a1 = np.random.randint(0,10,size=(3,8))
a2 = np.random.randint(0,10,size=(3,1))
a3 = a2-a1
print(a1)
print(a2)
print(a3)

[[3 3 5 9 9 3 9 3]
 [6 7 2 4 5 9 8 2]
 [5 1 4 3 0 1 2 6]]
[[9]
 [6]
 [9]]
[[ 6  6  4  0  0  6  0  6]
 [ 0 -1  4  2  1 -3 -2  4]
 [ 4  8  5  6  9  8  7  3]]


In [6]:
# 3.与列数相同并且只有1行的数组之间的运算
a1 = np.random.randint(0,10,size=(3,8))
a2 = np.random.randint(0,10,size=(1,8))
a3 = a1 + a2
print(a1)
print(a2)
print(a3)

[[2 4 2 5 8 3 2 1]
 [3 8 1 5 3 3 2 8]
 [7 8 0 8 0 0 4 5]]
[[1 3 7 7 9 1 0 4]]
[[ 3  7  9 12 17  4  2  5]
 [ 4 11  8 12 12  4  2 12]
 [ 8 11  7 15  9  1  4  9]]


## 广播原则
如果两个数组的后缘难度（即从末尾开始算起的维度）的轴长度相符或者其中一方发长度为1，则认为他们是广播兼容的。

# 总结：
1.数组和数字直接进行运算是没有问题的  
2.两个shape相同的数组是可以进行运算的。  
3.如果两个shape不同的数组，想要进行运算，那么要看他们是否满足广播原则。