reshape和resize方法，两个方法都是用来修改数组形状的，但是有一些不同。

In [1]:
import numpy as np

In [2]:
# 1.reshape是将数组转换成指定的形状，然后返回转换后的结果
# 对于原数组的形状是不会发生改变的
a1 = np.random.randint(0,10,size=(3,4))
print(a1)
a2 = a1.reshape((2,6))
print(a1)
print(a2)

[[3 5 5 7]
 [9 7 9 3]
 [6 5 5 0]]
[[3 5 5 7]
 [9 7 9 3]
 [6 5 5 0]]
[[3 5 5 7 9 7]
 [9 3 6 5 5 0]]


In [3]:
# resize是将数组转换成指定的形状，会直接修改数组本身，并不会返回任何值
a1 = np.random.randint(0,10,size=(3,4))
print(a1)
a2 = a1.resize((2,6))
print(a1)
print(a2)

[[1 3 3 1]
 [1 2 8 3]
 [6 7 9 8]]
[[1 3 3 1 1 2]
 [8 3 6 7 9 8]]
None


flatten和ravel方法都是将多维数组转换为一维数组，但是有以下不同

In [4]:
# 1.flatten是将数组转换为一维数组后，然后将这个拷贝返回去
# 所以后续对这个返回值进行修改不会影响之前的数组
a1 = np.random.randint(0,10,size=(3,4))
print(a1)
a2 = a1.flatten()
print(a2)
print(a1)

[[8 3 6 1]
 [8 6 9 7]
 [6 6 2 0]]
[8 3 6 1 8 6 9 7 6 6 2 0]
[[8 3 6 1]
 [8 6 9 7]
 [6 6 2 0]]


In [5]:
a2[0] = 88
print(a1[0,0])

8


In [7]:
# 2.ravel是将数组转换为一维数组后，将这个视图（可以理解为引用）返回回去
# 所以后续对这个返回值进行修改会影响之前的数组
a3 = a1.ravel()
a3[0] = 88
print(a1[0,0])

88


##### 如果有多个数组想要组合在一起，也可以通过其中的一些函数来实现

In [8]:
# vstack:将数组按垂直方向进行叠加。数组的列数必须相同才能叠加。
a1 = np.random.randint(0,10,size=(3,5))
a2 = np.random.randint(0,10,size=(1,5))
a3 = np.vstack([a1,a2])
print(a1)
print(a2)
print(a3)

[[8 5 7 5 8]
 [3 7 0 3 2]
 [8 7 2 7 8]]
[[0 1 6 0 9]]
[[8 5 7 5 8]
 [3 7 0 3 2]
 [8 7 2 7 8]
 [0 1 6 0 9]]


In [9]:
# hstack:将数组按水平方向进行叠加。数组的行必须相同才能叠加。
a1 = np.random.randint(0,10,size=(3,2))
a2 = np.random.randint(0,10,size=(3,1))
a3 = np.hstack([a1,a2])
print(a1)
print(a2)
print(a3)

[[0 9]
 [9 6]
 [8 0]]
[[2]
 [6]
 [1]]
[[0 9 2]
 [9 6 6]
 [8 0 1]]


In [14]:
# concatenate([],axis):将两个数组进行叠加，但是具体是按水平方向还是按垂直方向要看axis的参数
# 如果axis=0，那么代表的是往垂直方向叠加；如果axis=1，那么代表的是往水平方向上叠加
# 如果axis=None，那么将会两个数组组合成一个一维数组。需要注意的是如果往水平方向上叠加，那么行数必须相同
# 如果是往垂直方向叠加，那么列必须相同
a = np.array([[1,2],[3,4]])
b = np.array([[5,6]])
np.concatenate((a,b),axis=0)
np.concatenate((a,b.T),axis=1)
np.concatenate((a,b),axis=None)

array([1, 2, 3, 4, 5, 6])

### 数组的切割

In [15]:
# hsplit：按照水平方向进行切割。
# 用于指定分割成几列，可以使用数字来代表分成几部分，也可以使用数组来代表分割的地方。
hs1 = np.random.randint(0,10,size=(3,4))
print(hs1)

[[3 1 9 5]
 [0 7 7 5]
 [6 2 9 2]]


In [16]:
np.hsplit(hs1,2)#分割成两部分

[array([[3, 1],
        [0, 7],
        [6, 2]]),
 array([[9, 5],
        [7, 5],
        [9, 2]])]

In [18]:
np.hsplit(hs1,[1,2]) #代表在下标为1的地方切一刀，下标为2的地方切一刀，分成三部分

[array([[3],
        [0],
        [6]]),
 array([[1],
        [7],
        [2]]),
 array([[9, 5],
        [7, 5],
        [9, 2]])]

In [19]:
vs1 = np.random.randint(0,10,size=(4,5))
print(vs1)

[[8 6 3 9 9]
 [5 8 8 9 0]
 [2 6 5 1 7]
 [8 4 7 6 5]]


In [24]:
# vsplit:按照垂直方向进行切割。
# 用于指定分割成几行，可以使用数字来代表分成几部分，也可以使用数组来代表分割的地方。
np.vsplit(vs1,4)

[array([[8, 6, 3, 9, 9]]),
 array([[5, 8, 8, 9, 0]]),
 array([[2, 6, 5, 1, 7]]),
 array([[8, 4, 7, 6, 5]])]

In [21]:
np.vsplit(vs1,[1,3])

[array([[8, 6, 3, 9, 9]]),
 array([[5, 8, 8, 9, 0],
        [2, 6, 5, 1, 7]]),
 array([[8, 4, 7, 6, 5]])]

In [27]:
# split/array_split(array,indicate_or_seciont,axis):用于指定切割方式，在切割的时候需要指定的是按照行还是列
# axis=1代表按照列，axis=0代表按照行
print(hs1)
print(np.split(hs1,4,axis=1))
print(vs1)
print(np.split(vs1,4,axis=0))

[[3 1 9 5]
 [0 7 7 5]
 [6 2 9 2]]
[array([[3],
       [0],
       [6]]), array([[1],
       [7],
       [2]]), array([[9],
       [7],
       [9]]), array([[5],
       [5],
       [2]])]
[[8 6 3 9 9]
 [5 8 8 9 0]
 [2 6 5 1 7]
 [8 4 7 6 5]]
[array([[8, 6, 3, 9, 9]]), array([[5, 8, 8, 9, 0]]), array([[2, 6, 5, 1, 7]]), array([[8, 4, 7, 6, 5]])]


## 数组（矩阵）转置和轴对换

In [28]:
# 可以使用ndarray的T属性返回转置的结果
a1 = np.arange(0,24).reshape((4,6))
print(a1)
a2 = a1.T
print(a2)

[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]
[[ 0  6 12 18]
 [ 1  7 13 19]
 [ 2  8 14 20]
 [ 3  9 15 21]
 [ 4 10 16 22]
 [ 5 11 17 23]]


In [31]:
# 也可以使用transpose方法，该方法返回的是一个View，即修改返回值会影响到原来数组
a1 = np.random.randint(0,10,size=(2,4))
print(a1)
a2 = a1.transpose()
print(a2)
a2[0] = 88
print(a1)

[[9 8 7 4]
 [7 8 0 2]]
[[9 7]
 [8 8]
 [7 0]
 [4 2]]
[[88  8  7  4]
 [88  8  0  2]]


In [32]:
# 为什么要进行矩阵转置呢，有时候在做一些计算的时候需要用到。
# 比如做矩阵的内积的时候。就必须将矩阵进行转置后再乘以之前的矩阵：
a1 = np.arange(0,24).reshape((4,6))
a2 = a1.T
print(a1.dot(a2))

[[  55  145  235  325]
 [ 145  451  757 1063]
 [ 235  757 1279 1801]
 [ 325 1063 1801 2539]]


# 数组的形状改变
1.reshape和resize都是重新定义形状的。但是reshape不会修改数组本身，而是将修改后的结果返回回去，而resize是直接修改数组  
2.flatten和ravel都是用来将数组边成一维数组的，并且他们都不会对原数组造成修改，但是flatten返回的是一个拷贝，所以对flatten的返回值的修改不会影响到原来数组，而ravel返回的是一个View，那么对返回值的修改会影响到原来数组的值。

# 数组的叠加：
hstack代表在水平方向叠加，如果想要叠加成功，那么他们的行必须一致。
vstack代表在垂直方向叠加，如果想要叠加成功，那么他们的列必须一致。
concatenate可以手动的指定axis参数具体在哪个方向叠加，如果axis=0，代表在水平方向叠加，如果axis=1，代表在垂直方向叠加，如果axis=None，那么会先进行叠加，再转换成1维数组。
# 数组的切割:
1.hsplit代表在水平方向切割，按列进行分割的。他的切割方式有两种，第一种就是直接指定平均切割成多少列，第二种就是指定切割的下标值。    
2.vsplit代表在垂直方向进行切割，按行进行切割。他的切割方式跟hsplit一样。   
3.split/array_split是手动的指定axis参数，axis=0,代表按行进行切割，axis=1，代表按列进行切割。  
# 矩阵转置：
1.可以通过ndarray.T的形式进行转置。  
2.也可以通过ndarray.transpose()进行转置，这个方法返回的是一个View，所以对返回值上进行修改，会影响到原来的数组。