reshape和resize方法，两个方法都是用来修改数组形状的，但是有一些不同。

In [1]:
import numpy as np

In [2]:
# 1.reshape是将数组转换成指定的形状，然后返回转换后的结果
# 对于原数组的形状是不会发生改变的
a1 = np.random.randint(0,10,size=(3,4))
print(a1)
a2 = a1.reshape((2,6))
print(a1)
print(a2)

[[3 5 5 7]
 [9 7 9 3]
 [6 5 5 0]]
[[3 5 5 7]
 [9 7 9 3]
 [6 5 5 0]]
[[3 5 5 7 9 7]
 [9 3 6 5 5 0]]


In [3]:
# resize是将数组转换成指定的形状，会直接修改数组本身，并不会返回任何值
a1 = np.random.randint(0,10,size=(3,4))
print(a1)
a2 = a1.resize((2,6))
print(a1)
print(a2)

[[1 3 3 1]
 [1 2 8 3]
 [6 7 9 8]]
[[1 3 3 1 1 2]
 [8 3 6 7 9 8]]
None


flatten和ravel方法都是将多维数组转换为一维数组，但是有以下不同

In [4]:
# 1.flatten是将数组转换为一维数组后，然后将这个拷贝返回去
# 所以后续对这个返回值进行修改不会影响之前的数组
a1 = np.random.randint(0,10,size=(3,4))
print(a1)
a2 = a1.flatten()
print(a2)
print(a1)

[[8 3 6 1]
 [8 6 9 7]
 [6 6 2 0]]
[8 3 6 1 8 6 9 7 6 6 2 0]
[[8 3 6 1]
 [8 6 9 7]
 [6 6 2 0]]


In [5]:
a2[0] = 88
print(a1[0,0])

8


In [6]:
# 2.ravel是将数组转换为一维数组后，将这个视图（可以理解为引用）返回回去
# 所以后续对这个返回值进行修改会影响之前的数组
a3 = a1.ravel()
a3[0] = 88
print(a1[0,0])

88


# 数组的形状改变
1.reshape和resize都是重新定义形状的。但是reshape不会修改数组本身，而是将修改后的结果返回回去，而resize是直接修改数组  
2.flatten和ravel都是用来将数组边成一维数组的，并且他们都不会对原数组造成修改，但是flatten返回的是一个拷贝，所以对flatten的返回值的修改不会影响到原来数组，而ravel返回的是一个View，那么对返回值的修改会影响到原来数组的值。