In [1]:
import numpy as np

文件保存：
使用np.savetxt来实现：  
np.savetxt(frame,array,fmt,delimiter,newline,header,footer,comments,encoding)    
frame:文件名或文件句柄   
array:要保存到文件的数据   
fmt:保存的格式  
delimiter:分割字符串，默认是空格   
newline:字符串或字符分隔线   
header:将在文件开头写入的字符串   
footer：将在文件末尾写入的字符串   
comments：将附加到header和footer字符串的字符串   
encoding：文件编码

In [2]:
scores = np.random.randint(0,100,size=(20,2))
scores

array([[16, 34],
       [96, 27],
       [16, 59],
       [72, 54],
       [51,  9],
       [55, 18],
       [50, 19],
       [55, 14],
       [72, 86],
       [67, 61],
       [73, 14],
       [69,  9],
       [ 7, 39],
       [32, 88],
       [18, 83],
       [71, 46],
       [95, 66],
       [99, 24],
       [78, 27],
       [53, 30]])

In [4]:
np.savetxt("score.csv",scores,delimiter=',',header="英语,数学",comments="",fmt="%d")

读取文件：
使用np.loadtxt来实现，相关函数描述如下:
np.loadtxt(frame, dtype=np.float, delimiter=None, unpack=False)
* frame：文件、字符串或产生器，可以是.gz或.bz2的压缩文件。
* dtype：数据类型，可选。
* delimiter：分割字符串，默认是任何空格。
* skiprows：跳过前面x行。
* usecols：读取指定的列，用元组组合。
* unpack：如果True，读取出来的数组是转置后的。

In [6]:
b = np.loadtxt("score.csv",dtype=int,delimiter=',',skiprows=1)
b

array([[16, 34],
       [96, 27],
       [16, 59],
       [72, 54],
       [51,  9],
       [55, 18],
       [50, 19],
       [55, 14],
       [72, 86],
       [67, 61],
       [73, 14],
       [69,  9],
       [ 7, 39],
       [32, 88],
       [18, 83],
       [71, 46],
       [95, 66],
       [99, 24],
       [78, 27],
       [53, 30]])

numpy独有的存储解决方案：
存储：np.save(frame,array)或np.savez(frame,array),前者函数的扩展名是`.npy`，后者的扩展名是`.npz`，后者是经过压缩的   
加载：np.load(fname)

In [7]:
c = np.random.randint(0,10,size=(2,3))
print(c)
np.save("c",c)

[[8 5 9]
 [6 0 9]]


In [8]:
c1 = np.load("c.npy")
c1

array([[8, 5, 9],
       [6, 0, 9]])

In [11]:
d = np.random.randint(0,10,size=(2,3,4))
# np.savetxt("d.csv",d)
np.save("d",d)

# 总结：
1.np.savetxt和np.loadtxt一般用来操作csv文件，它可以设置header，但是不能存储三维以上的数组。  
2.np.save和np.load一般用来存储非文本类型的文件，它不可以设置header，但是可以存储三维以上的数组。   
3.如果想专门的操作CSV文件，还有csv模块。