In [2]:
import numpy as np

1. 数组`a = np.random.rand(3,2,3)`能和`b = np.random.rand(3,2,2)`进行运算吗？能和`c = np.random.rand(3,1,1)`进行运算吗？请说明结果的原因。

In [3]:
a = np.random.rand(3,2,3)
b = np.random.rand(3,2,2)
a + b
# 答案：a和b不能参与运算，因为不满足广播的机制

ValueError: operands could not be broadcast together with shapes (3,2,3) (3,2,2) 

In [6]:
a = np.random.rand(3,2,3)
c = np.random.rand(3,1,1)
print(a)
print(c)
a + c
# 答案：a和c可以参与运算，因为满足广播机制（a和b的形状值虽然不相等，但是不相等的地方都是等于1）

[[[0.52861786 0.88262433 0.49510378]
  [0.29364156 0.01556228 0.84110193]]

 [[0.49489336 0.59547142 0.01519171]
  [0.15537244 0.46482167 0.34892366]]

 [[0.14176147 0.58978936 0.33785688]
  [0.17597699 0.23812355 0.92497561]]]
[[[0.56599239]]

 [[0.61434546]]

 [[0.36079343]]]


array([[[1.09461025, 1.44861673, 1.06109618],
        [0.85963395, 0.58155467, 1.40709433]],

       [[1.10923882, 1.20981688, 0.62953717],
        [0.7697179 , 1.07916713, 0.96326912]],

       [[0.5025549 , 0.95058279, 0.69865031],
        [0.53677041, 0.59891698, 1.28576904]]])

2. 想要将数组`a = np.arange(15).reshape(3,5)`和`b = np.arange(100,124).reshape(6,4)`叠加在一起，其中`a`在`b`的上面，并且在`b`的第1列后面（下标从0开始）新增一列，用0来填充。

In [7]:
# 第二题答案：
# 1.准备好数据
a = np.arange(15).reshape(3,5)
b = np.arange(100,124).reshape(6,4)
# 2.因为b只有4列，无法直接和a堆叠，并且题目要求要在第一列后面添加一列
# 所以先将b数组在下标为1的地方切割，然后添加完0数组后再进行拼接
bsplits = np.hsplit(b,[2])
# 3.创建一个全0的6行1列的数组
bzero = np.zeros((6,1))
# 4.将b的前半部分，0，b的后半部分组合在一起形成一个新的数组
c = np.hstack([bsplits[0],bzero,bsplits[1]])
# 5.将a和新生成的数组进行堆叠得到结果
result = np.vstack([a,c])
result

array([[  0.,   1.,   2.,   3.,   4.],
       [  5.,   6.,   7.,   8.,   9.],
       [ 10.,  11.,  12.,  13.,  14.],
       [100., 101.,   0., 102., 103.],
       [104., 105.,   0., 106., 107.],
       [108., 109.,   0., 110., 111.],
       [112., 113.,   0., 114., 115.],
       [116., 117.,   0., 118., 119.],
       [120., 121.,   0., 122., 123.]])

3. 将数组`a = np.random.rand(4,5)`扁平化成一维数组，可以使用`flatten`和`ravel`，对两者的返回值进行操作，哪个会影响到数组`a`？对会影响到`a`数组的那个函数，请说明原因。

In [9]:
# 第三题答案：
a = np.random.rand(4,5)
a1 = a.flatten()
a1[0] = 10
print(a)
print('='*30)
a2 = a.ravel()
a2[0] = 20
print(a)
# 结果：ravel会影响原来的数组。原因是因为ravel返回的是一个浅拷贝（视图），虽然在栈中的内存不一样，但是指向的堆区的内存地址还是一样
# 所以修改了a2,会影响到原来堆区的值。但是flatten返回的是一个深拷贝，也即栈区和堆区都进行了拷贝。

[[0.35230824 0.80393808 0.28507039 0.08024001 0.31404108]
 [0.75122143 0.97510412 0.48397677 0.90645693 0.17172821]
 [0.98978892 0.33049243 0.19139348 0.25470182 0.42878057]
 [0.70483148 0.78936745 0.59339431 0.10099746 0.63417672]]
[[20.          0.80393808  0.28507039  0.08024001  0.31404108]
 [ 0.75122143  0.97510412  0.48397677  0.90645693  0.17172821]
 [ 0.98978892  0.33049243  0.19139348  0.25470182  0.42878057]
 [ 0.70483148  0.78936745  0.59339431  0.10099746  0.63417672]]


4.使用numpy自带的csv方法读取出stock.csv文件中preClosePrice、openPrice、highestPrice、lowestPrice的数据（提示：使用skiprows和usecols参数）。

In [10]:
stocks = np.loadtxt("stock.csv",dtype=np.float,delimiter=",",skiprows=1,usecols=[6,7,8,9])
stocks

C:\Users\winlab\AppData\Local\Temp/ipykernel_15168/3236746195.py:1: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  stocks = np.loadtxt("stock.csv",dtype=np.float,delimiter=",",skiprows=1,usecols=[6,7,8,9])


array([[13.38 , 13.4  , 13.48 , 12.96 ],
       [31.22 , 30.5  , 32.03 , 30.5  ],
       [25.56 , 25.41 , 26.4  , 25.18 ],
       ...,
       [ 0.507,  0.507,  0.508,  0.507],
       [ 1.675,  1.67 ,  1.69 ,  1.67 ],
       [ 0.976,  0.976,  0.988,  0.976]])