In [1]:
import numpy as np

In [2]:
data = np.random.randint(0,10,size=(3,5))
data

array([[3, 0, 9, 5, 1],
       [9, 3, 1, 2, 7],
       [1, 6, 5, 6, 4]])

In [4]:
data = data.astype(float)
data[0,1] = np.nan
data

array([[ 3., nan,  9.,  5.,  1.],
       [ 9.,  3.,  1.,  2.,  7.],
       [ 1.,  6.,  5.,  6.,  4.]])

In [5]:
data/0

C:\Users\winlab\AppData\Local\Temp/ipykernel_14892/1771165735.py:1: RuntimeWarning: divide by zero encountered in true_divide
  data/0


array([[inf, nan, inf, inf, inf],
       [inf, inf, inf, inf, inf],
       [inf, inf, inf, inf, inf]])

In [6]:
np.NAN == np.NAN

False

In [7]:
data[0,1]*2

nan

In [8]:
data[1,2] = np.NAN
data

array([[ 3., nan,  9.,  5.,  1.],
       [ 9.,  3., nan,  2.,  7.],
       [ 1.,  6.,  5.,  6.,  4.]])

In [9]:
data[~np.isnan(data)]

array([3., 9., 5., 1., 9., 3., 2., 7., 1., 6., 5., 6., 4.])

In [10]:
lines = np.where(np.isnan(data))[0]
np.delete(data,lines,axis=0)

array([[1., 6., 5., 6., 4.]])

In [13]:
scores = np.loadtxt("nan_scores.csv",delimiter=',',skiprows=1,encoding="utf-8",dtype=str)
print(scores)
scores[scores==""] = np.NAN
scores1 = scores.astype(float)
print(scores1)
scores1[np.isnan(scores1)] = 0
print(scores1)
# 除了delete用axis=0表示行以外，其他的大部分函数都是axis=1表示行
scores1.sum(axis=1)

[['59' '89']
 ['90' '32']
 ['78' '45.5']
 ['34' '']
 ['' '56']
 ['23' '56']]
[[59.  89. ]
 [90.  32. ]
 [78.  45.5]
 [34.   nan]
 [ nan 56. ]
 [23.  56. ]]
[[59.  89. ]
 [90.  32. ]
 [78.  45.5]
 [34.   0. ]
 [ 0.  56. ]
 [23.  56. ]]


array([148. , 122. , 123.5,  34. ,  56. ,  79. ])

In [18]:
scores2 = scores.astype(float)
print(scores2)
print(scores2.shape)
for x in range(scores2.shape[1]):
    col = scores2[:,x]
    non_nan_col = col[~np.isnan(col)]
    mean = non_nan_col.mean()
    col[np.isnan(col)] = mean
scores2

[[59.  89. ]
 [90.  32. ]
 [78.  45.5]
 [34.   nan]
 [ nan 56. ]
 [23.  56. ]]
(6, 2)


array([[59. , 89. ],
       [90. , 32. ],
       [78. , 45.5],
       [34. , 55.7],
       [56.8, 56. ],
       [23. , 56. ]])