In [1]:
import numpy as np

## np.random.seed：

用于指定随机数生成时所用算法开始的整数值，如果使用相同的`seed()`值，则每次生成的随即数都相同，如果不设置这个值，则系统根据时间来自己选择这个值，此时每次生成的随机数因时间差异而不同。一般没有特殊要求不用设置。

In [10]:
# np.random.seed(1)
np.random.rand()
np.random.rand(2,3)

array([[0.31342418, 0.69232262, 0.87638915],
       [0.89460666, 0.08504421, 0.03905478]])

## np.random.rand：

生成一个值为`[0,1)`之间的数组，形状由参数指定，如果没有参数，那么将返回一个随机值。

## np.random.randn：

生成均值\(μ\)为0，标准差（σ）为1的标准正态分布的值。

In [11]:
np.random.randn()

-0.17242820755043575

## np.random.randint：

生成指定范围内的随机数，并且可以通过`size`参数指定维度。

## np.random.choice：

从一个列表或者数组中，随机进行采样。或者是从指定的区间中进行采样，采样个数可以通过参数指定

In [12]:
data = np.arange(5)
data

array([0, 1, 2, 3, 4])

In [14]:
np.random.choice(data,size=(3,4))
np.random.choice(10,size=(2,5))

array([[5, 9, 3, 6, 8],
       [0, 2, 7, 7, 9]])

## np.random.shuffle：

把原来数组的元素的位置打乱。

In [15]:
data1 = np.arange(10)
print(data1)
np.random.shuffle(data1)
print(data1)

[0 1 2 3 4 5 6 7 8 9]
[9 6 1 8 5 0 2 4 3 7]
